// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbCIye3TzicLf8ss8m_On9V8B46BQ75g',
    appId: '1:4029397392:web:84c41e059e74bf5c0cdb15',
    messagingSenderId: '4029397392',
    projectId: 'ping-me-285fd',
    authDomain: 'ping-me-285fd.firebaseapp.com',
    storageBucket: 'ping-me-285fd.firebasestorage.app',
    measurementId: 'G-6RY6GYMXZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPhHbVUIoI2q5bBrGnqQCBO-7dzVssRE',
    appId: '1:4029397392:android:8e1ffd83112aec860cdb15',
    messagingSenderId: '4029397392',
    projectId: 'ping-me-285fd',
    storageBucket: 'ping-me-285fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqiuGMaV9KoldTGXf4dFQRem_yAITwFgQ',
    appId: '1:4029397392:ios:579ccb3a2413c3240cdb15',
    messagingSenderId: '4029397392',
    projectId: 'ping-me-285fd',
    storageBucket: 'ping-me-285fd.firebasestorage.app',
    iosBundleId: 'com.example.pingMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqiuGMaV9KoldTGXf4dFQRem_yAITwFgQ',
    appId: '1:4029397392:ios:579ccb3a2413c3240cdb15',
    messagingSenderId: '4029397392',
    projectId: 'ping-me-285fd',
    storageBucket: 'ping-me-285fd.firebasestorage.app',
    iosBundleId: 'com.example.pingMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxbCIye3TzicLf8ss8m_On9V8B46BQ75g',
    appId: '1:4029397392:web:0ee025b485cd5feb0cdb15',
    messagingSenderId: '4029397392',
    projectId: 'ping-me-285fd',
    authDomain: 'ping-me-285fd.firebaseapp.com',
    storageBucket: 'ping-me-285fd.firebasestorage.app',
    measurementId: 'G-T78TK52JT1',
  );
}
